---
- name: Install Docker
  hosts: ec2_servers
  become: yes
  become_user: root
  tasks:
    - name: Install Docker
      ansible.builtin.dnf:
        name: docker
        update_cache: true
        state: present

- name: Install Docker Compose
  hosts: ec2_servers
  vars_files: project-vars.yaml
  become: yes
  tasks:
    - name: Create docker-compose directory
      file:
        path: /home/ec2-user/.docker/cli-plugins/
        state: directory
    - name: Get architecture of remote machine
      shell: uname -m
      register: remote_arch
    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-linux-{{ remote_arch.stdout }}
        dest: /home/ec2-user/.docker/cli-plugins/docker-compose
        mode: +x

- name: Start Docker
  hosts: ec2_servers
  become: yes
  become_user: root
  tasks:
    - name: Start docker daemon
      ansible.builtin.systemd_service:
        name: docker
        state: started

- name: Add ec2-user to docker group
  hosts: ec2_servers
  become: yes
  become_user: root
  tasks:
    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
    - name: Reconnect to server session
      meta: reset_connection

- name: Start Docker container
  hosts: ec2_servers
  vars_files: project-vars.yaml
  tasks:
    - name: Copy docker compose file to Remote Server
      copy:
        src: ./docker-compose.yaml
        dest: /home/ec2-user/
    - name: Login to Docker Repository
      community.docker.docker_login:
        username: nguyenmanhtrinh
        password: '{{docker_password}}'
    - name: Start Container from Compose
      community.docker.docker_compose_v2:
        project_src: /home/ec2-user/
        state: present


        
