---
- name: Install Docker 
  hosts: droplets
  tasks:
    - name: update apt repo and cache 
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install Docker 
      apt:
        name: docker.io
        state: present

- name: Ensure Docker is started and enabled 
  hosts: droplets
  tasks:
    - name: Start and enable Docker
      ansible.builtin.systemd_service:
        name: docker
        state: started
      
- name: Create Jenkins user and add Jenkins to Sudo, Docker groups
  hosts: droplets
  tasks: 
    - name: Create Jenkins user 
      user:
        name: jenkin
        groups: docker, sudo
        append: yes 
        create_home: yes # ensures a home directory like /home/jenkin is created.
        shell: /bin/bash
    - name: Create ~/.ansible/tmp for jenkin user 
      file:
        path: /home/jenkin/.ansible/tmp
        state: directory
        owner: jenkin
        group: jenkin
        mode: '0700'

- name: Run Jenkins as a jenkin user by using Docker 
  hosts: droplets
  become_user: jenkin 
  become: yes
  tasks: 
    - name: Create Jenkin container 
      community.docker.docker_container:
        name: my-jenkin 
        image: jenkins/jenkins:lts
        volumes:
          - jenkins_home:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock
        published_ports:
          - 8080:8080
          - 50000:50000
        detach: true
        state: started 
        restart_policy: unless-stopped

- name: Run command inside Jenkin Container 
  hosts: droplets
  become_user: jenkin
  become: yes
  tasks:
    - name: Check if setup marker exists
      community.docker.docker_container_exec:
        container: my-jenkin
        user: root
        command: test -f /var/jenkins_home/.jenkins_setup_done
      register: setup_marker
      ignore_errors: yes
    - debug: msg={{setup_marker}}

    - name: Create .jenkins_setup_done file 
      community.docker.docker_container_exec:
        container: my-jenkin
        user: root
        command: touch -f /var/jenkins_home/.jenkins_setup_done
      when: setup_marker.rc != 0
      
    - debug: msg={{setup_marker}}
    - name: Update apt package 
      community.docker.docker_container_exec:
        container: my-jenkin
        user: root
        command: apt-get update
      when: setup_marker.rc != 0
    - name: Install curl 
      community.docker.docker_container_exec:
        container: my-jenkin
        user: root
        command: apt-get install -y curl
      when: setup_marker.rc != 0
    - name: Download nodejs and npm 
      community.docker.docker_container_exec:
        container: my-jenkin
        user: root 
        command: curl -sL https://deb.nodesource.com/setup_20.x -o nodesource_setup.sh
      when: setup_marker.rc != 0
    - name: Run nodesource_setup.sh
      community.docker.docker_container_exec:
        container: my-jenkin
        user: root 
        command: bash nodesource_setup.sh
      when: setup_marker.rc != 0
    - name: Install Nodejs and npm 
      community.docker.docker_container_exec:
        container: my-jenkin
        user: root 
        command: apt-get install nodejs -y
      when: setup_marker.rc != 0
    - name: Install Docker inside jenkins container 
      community.docker.docker_container_exec:
        container: my-jenkin
        user: root 
        command: bash -c "curl https://get.docker.com/ > dockerinstall && chmod 777 dockerinstall && ./dockerinstall"
      when: setup_marker.rc != 0
    - name: Set correct Permission on docker.sock
      community.docker.docker_container_exec:
        container: my-jenkin
        user: root
        command: chmod 666 /var/run/docker.sock
      when: setup_marker.rc != 0


  
