---
- name: Make sure acl (Access Control List) package available
  hosts: aws_ec2
  become: yes
  become_user: root
  tasks:
    - name: Install acl
      ansible.builtin.dnf:
        name: acl 
        state: present

- name: Install Docker
  hosts: aws_ec2
  become: yes
  become_user: root
  tasks:
    - name: Install Docker
      ansible.builtin.dnf:
        name: docker
        update_cache: true
        state: present

- name: Create new Linux User
  hosts: aws_ec2
  become: yes
  vars_files: project-vars.yaml
  roles:
    - create_user


- name: Install Docker Compose
  hosts: aws_ec2
  become: yes
  become_user: "{{linux_name}}"
  vars_files: 
    project-vars.yaml
  tasks:
    - name: Create docker-compose directory
      file:
        path: /home/{{linux_name}}/.docker/cli-plugins/
        state: directory
    - name: Get architecture of remote machine
      shell: uname -m
      register: remote_arch
    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-linux-{{ remote_arch.stdout }}
        dest: /home/{{linux_name}}/.docker/cli-plugins/docker-compose
        mode: +x

- name: Start Docker
  hosts: aws_ec2
  become: yes
  become_user: root
  tasks:
    - name: Start docker daemon
      ansible.builtin.systemd_service:
        name: docker
        state: started


- name: Start Docker container
  hosts: aws_ec2
  vars_files: project-vars.yaml
  become: yes
  become_user: "{{linux_name}}"
  roles:
    - start_containers


        

