---
- name: Install java and net-tools
  hosts: 134.199.236.65
  tasks: 
    - name: Update apt repo and cache 
      apt: 
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install java version 8
      apt:
        name: openjdk-8-jre-headless
    - name: Install net tools
      apt: 
        name: net-tools
- name: Download and unpack nexus installer 
  hosts: 134.199.236.65
  tasks: 
    - name: Check Nexus folder status 
      stat: 
        path: /opt/nexus
      register: stat_results
    - name: change dir to /opt and download nexus 
      get_url:
        url: https://download.sonatype.com/nexus/3/nexus-3.80.0-06-linux-x86_64.tar.gz
        dest: /opt/
      register: nexus_package_result
    - name: Unpack nexus 
      unarchive:
        src: "{{nexus_package_result.dest}}"
        dest: /opt/
        remote_src: True
      when: not stat_results.stat.exists
    - name: Find Nexus folder 
      find:
        paths: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result
    - name: Rename Nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_results.stat.exists

- name: Create nexus user and make nexus owner of nexus and sonatype work
  hosts: 134.199.236.65
  tasks:
    - name: Create group nexus 
      group:
        name: nexus
        state: present
    - name: Create nexus user 
      user:
        name: nexus 
        group: nexus
    - name: Make nexus owner of nexus folder 
      file:
        path: /opt/nexus
        state: directory
        owner: nexus 
        group: nexus
        recurse: yes
    - name: Make nexus owner of sonatype folder 
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus 
        group: nexus
        recurse: yes

- name: Start nexus with nexus user 
  hosts: 134.199.236.65
  become: True
  become_user: nexus
  tasks:
    # - name: Set run_as_user nexus 
    #   blockinfile:
    #     path: /opt/nexus/bin/nexus.rc
    #     block: |
    #       run_as_user="nexus"
    - name: Start nexus 
      command: /opt/nexus/bin/nexus start 

- name: Verify if Nexus is running 
  hosts: 134.199.236.65
  become: True
  become_user: nexus
  tasks: 
    - name: Check with ps command 
      shell: ps aux | grep nexus 
      register: app_status 
    - debug: msg={{app_status.stdout_lines}}
    - name: Wait 1 minute 
      pause: 
        minutes: 1
    - name: Check with netstat 
      shell: netstat -ltpn 
      register: app_status
    - debug: msg={{app_status.stdout_lines}}



