---
- name: Install nodejs and npm
  hosts: 164.92.98.29
  vars_files:
    project-vars.yaml
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Create Linux user for node App
  hosts: 164.92.98.29
  vars_files:
    project-vars.yaml
  tasks: 
    - name: Create Linux user
      user: 
        name: "{{linux_name}}"
        comment: "{{linux_name}} Admin"  
        group: admin
      register: user_creation_result
    - debug: msg={{user_creation_result}}

- name: Deploy Nodejs App
  hosts: 164.92.98.29
  vars_files:
    project-vars.yaml
  become: true
  become_user: "{{linux_name}}"
  tasks:
    - name: Copy file to Remote server
      copy:
        src: "{{node_file_location}}"
        dest: "{{destination}}/nodejs-app-1.0.0.tgz" 
    - name: Unpack the Nodejs file
      unarchive:
        src: "{{destination}}/nodejs-app-1.0.0.tgz"
        dest: "{{destination}}/"
        remote_src: yes
    - name: Install Dependencies
      community.general.npm:
        path: "{{destination}}/package"
    - name: Start Application
      command: 
        chdir: "{{destination}}/package/app"
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status}}

