---
- name: Configure nginx server
  hosts: droplets
  tasks:
  - name: install nginx server
    apt:
      name: nginx
      state: absent
  # - name: start nginx server
  #   service:
  #     name: nginx
  #     state: started