- name: Create new Linux user
  user:
    name: "{{linux_name}}"
    groups: adm, docker
    create_home: yes
    
- name: Create ~/.ansible/tmp for tim
  file:
    path: /home/{{linux_name}}/.ansible/tmp
    state: directory
    owner: "{{linux_name}}"
    group: "{{linux_name}}"
    mode: '0700'